[package]
name = "pathy"
version = "0.1.0"
edition = "2024"
description = "A modern, visual CLI for exploring and editing PATH."
license = "MIT"
repository = "https://github.com/aognio/pathy"
homepage = "https://github.com/aognio/pathy"
documentation = "https://github.com/aognio/pathy#readme"
readme = "README.md"
keywords = ["cli", "path", "terminal", "shell"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29.0"
is-terminal = "0.1"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
terminal_size = "0.4.4"
